title: Guild War2
author: Panoramedia
paginate: 5
paginate_path: /page:num/

description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll


sass:
    style: compressed
